name: Codebase checks
run-name: Codebase checks

on:
  workflow_dispatch:
  pull_request: 
    branches: 
      - "**"
  push:
    branches:
      - main

concurrency: 
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: false
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: "**/**/pnpm-lock.yaml"
          cache: 'pnpm'
    
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    name: "Build check"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: false
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: "**/**/pnpm-lock.yaml"
          cache: 'pnpm'
  
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

